//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.DAL
{
    using Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        [Key]
        public int ReservationId { get; set; }
        public int Quantity { get; set; }
        public DateTime TimeStamp { get; set; }

        public enum Status
        {
            [Description("InProcess")]
            InProcess,
            [Description("Complete")]
            Complete
        };
        public Status StatusType { get; set; }
        public int ProjectionId { get; set; }
        public int UserId { get; set; }

        public Projection Projection { get; set; }
    }
}
